labels:
  platform: linux/amd64

when:
  - event: [push, pull_request, manual]

steps:
  lint:
    image: golang:1.24
    commands:
      - go vet ./...

  test:
    image: golang:1.24
    commands:
      - go test -v -race -count=1 ./...
    depends_on: [lint]
